formatter: "markdown"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

content: |-

    {{ .Header }}

    ## Examples

    ### Debian 11

    ```hcl
    {{ include "examples/debian11/main.tf" }}
    ```

    ### Debian 12

    ```hcl
    {{ include "examples/debian12/main.tf" }}
    ```

    ### OpenSuse

    ```hcl
    {{ include "examples/opensuse/main.tf" }}
    ```

    ### Fedora CoreOS

    ```hcl
    {{ include "examples/fedoracoreos/main.tf" }}
    ```

    ### Suse Linux Enterprise 15

    ```hcl
    {{ include "examples/sles15/main.tf" }}
    ```

    ### Example RockyLinux 8

    ```hcl
    {{ include "examples/rockylinux8/main.tf" }}
    ```

    ### Example RockyLinux 9

    ```hcl
    {{ include "examples/rockylinux9/main.tf" }}
    ```

    ### Example FreeBSD 13.1

    ```hcl
    {{ include "examples/freebsd131/main.tf" }}
    ```

    ### Example Ubuntu 20.04

    ```hcl
    {{ include "examples/ubuntu2004/main.tf" }}
    ```

    ### Example Ubuntu 22.04

    ```hcl
    {{ include "examples/ubuntu2204/main.tf" }}
    ```
    ### Example Ubuntu 24.04

    ```hcl
    {{ include "examples/ubuntu2404/main.tf" }}
    ```

    {{ .Inputs }}
    {{ .Modules }}
    {{ .Outputs }}
    {{ .Providers }}
    {{ .Resources }}
    {{ .Requirements }}
    {{ .Footer }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
<<<<<<< HEAD
    <!-- END_TF_DOCS -->
=======

    ## Example

    ```hcl
    {{ include "examples/rockylinux8/main.tf" }}
    ```

    ```hcl
    {{ include "examples/rockylinux9/main.tf" }}
    ```

    <!-- END_TF_DOCS -->    
>>>>>>> e67d73a (testing)

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
